[udm]
port = 19211

[daemon]
log_file_path = "./udm_daemon.log"

# [daemon.sqlite]
# db_path = "/workspaces/udm/.config/test_udm.db"

[postgres]
user="postgres"
db_port=5432

[drink_controller]
port = 53049