---
name: UDM Actions

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  formatting:
    name: Formatting Rust Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
  build:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
    - name: Install Ubuntu pre-requirements
      run: |
        sudo apt update &&  sudo apt install -y protobuf-compiler libprotobuf-dev 
      shell: bash
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Linting the Code Base
      uses: super-linter/super-linter@v6.6.0
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_MARKDOWN: false
        VALIDATE_JSCPD: false
        VALIDATE_RUST_2018: false
        VALIDATE_RUST_2015: false
        VALIDATE_RUST_CLIPPY: false
        VALIDATE_SHELL_SHFMT: false
        VALIDATE_CHECKOV: false
    - run: cargo build
      env: 
        PROTOC: "/usr/bin/protoc"
    - run: cargo test

